@echo off
echo ========================================
echo Smart Bins MQTT Broker Setup (Windows)
echo ========================================
echo.

REM Check if running as administrator
net session >nul 2>&1
if %errorLevel% neq 0 (
    echo ERROR: This script must be run as Administrator
    echo Right-click and select "Run as administrator"
    pause
    exit /b 1
)

echo [1/6] Checking for existing Mosquitto installation...
if exist "C:\Program Files\mosquitto\mosquitto.exe" (
    echo Mosquitto already installed at C:\Program Files\mosquitto\
    goto :configure
)

echo [2/6] Downloading Mosquitto MQTT Broker...
echo Please download Mosquitto from: https://mosquitto.org/download/
echo Look for "mosquitto-2.0.18-install-windows-x64.exe" or latest version
echo.
echo After downloading:
echo 1. Run the installer as Administrator
echo 2. Install to default location (C:\Program Files\mosquitto\)
echo 3. Press any key here to continue...
pause >nul

REM Verify installation
if not exist "C:\Program Files\mosquitto\mosquitto.exe" (
    echo ERROR: Mosquitto not found after installation
    echo Please ensure Mosquitto is installed to C:\Program Files\mosquitto\
    pause
    exit /b 1
)

:configure
echo [3/6] Creating Mosquitto configuration...

REM Create mosquitto configuration directory
if not exist "C:\Program Files\mosquitto\config" mkdir "C:\Program Files\mosquitto\config"

REM Create main configuration file
echo # Mosquitto MQTT Broker Configuration for Smart Bins > "C:\Program Files\mosquitto\config\mosquitto.conf"
echo # Generated by Smart Bins setup script >> "C:\Program Files\mosquitto\config\mosquitto.conf"
echo. >> "C:\Program Files\mosquitto\config\mosquitto.conf"
echo # Network Configuration >> "C:\Program Files\mosquitto\config\mosquitto.conf"
echo listener 1883 >> "C:\Program Files\mosquitto\config\mosquitto.conf"
echo protocol mqtt >> "C:\Program Files\mosquitto\config\mosquitto.conf"
echo. >> "C:\Program Files\mosquitto\config\mosquitto.conf"
echo # Security Configuration >> "C:\Program Files\mosquitto\config\mosquitto.conf"
echo allow_anonymous false >> "C:\Program Files\mosquitto\config\mosquitto.conf"
echo password_file C:\Program Files\mosquitto\config\passwd >> "C:\Program Files\mosquitto\config\mosquitto.conf"
echo. >> "C:\Program Files\mosquitto\config\mosquitto.conf"
echo # Logging Configuration >> "C:\Program Files\mosquitto\config\mosquitto.conf"
echo log_dest file C:\Program Files\mosquitto\logs\mosquitto.log >> "C:\Program Files\mosquitto\config\mosquitto.conf"
echo log_type error >> "C:\Program Files\mosquitto\config\mosquitto.conf"
echo log_type warning >> "C:\Program Files\mosquitto\config\mosquitto.conf"
echo log_type notice >> "C:\Program Files\mosquitto\config\mosquitto.conf"
echo log_type information >> "C:\Program Files\mosquitto\config\mosquitto.conf"
echo connection_messages true >> "C:\Program Files\mosquitto\config\mosquitto.conf"
echo log_timestamp true >> "C:\Program Files\mosquitto\config\mosquitto.conf"
echo. >> "C:\Program Files\mosquitto\config\mosquitto.conf"
echo # Persistence >> "C:\Program Files\mosquitto\config\mosquitto.conf"
echo persistence true >> "C:\Program Files\mosquitto\config\mosquitto.conf"
echo persistence_location C:\Program Files\mosquitto\data\ >> "C:\Program Files\mosquitto\config\mosquitto.conf"

echo [4/6] Creating directories and setting permissions...
if not exist "C:\Program Files\mosquitto\logs" mkdir "C:\Program Files\mosquitto\logs"
if not exist "C:\Program Files\mosquitto\data" mkdir "C:\Program Files\mosquitto\data"

echo [5/6] Creating MQTT users...
cd /d "C:\Program Files\mosquitto"

REM Create password file with esp32_user
echo Creating user 'esp32_user' for ESP32 devices...
mosquitto_passwd.exe -c config\passwd esp32_user
if %errorLevel% neq 0 (
    echo ERROR: Failed to create password file
    pause
    exit /b 1
)

echo.
echo Creating user 'edge_processor' for edge processor...
mosquitto_passwd.exe config\passwd edge_processor
if %errorLevel% neq 0 (
    echo ERROR: Failed to add edge_processor user
    pause
    exit /b 1
)

echo [6/6] Installing and starting Mosquitto service...
REM Stop service if running
sc stop mosquitto >nul 2>&1

REM Delete existing service if it exists
sc delete mosquitto >nul 2>&1

REM Install service using sc command (modern method)
echo Installing Mosquitto as Windows service...
sc create mosquitto binPath= "\"C:\Program Files\mosquitto\mosquitto.exe\" -c \"C:\Program Files\mosquitto\config\mosquitto.conf\"" DisplayName= "Mosquitto MQTT Broker" start= auto
if %errorLevel% neq 0 (
    echo ERROR: Failed to install Mosquitto service
    echo Trying alternative installation method...
    
    REM Try using NSSM if available, otherwise start manually
    echo.
    echo The service installation failed. You have two options:
    echo.
    echo Option 1: Manual start (recommended for testing)
    echo   Run: mosquitto.exe -c "C:\Program Files\mosquitto\config\mosquitto.conf"
    echo.
    echo Option 2: Install NSSM (Non-Sucking Service Manager)
    echo   Download from: https://nssm.cc/download
    echo   Then run: nssm install mosquitto "C:\Program Files\mosquitto\mosquitto.exe"
    echo.
    echo For now, let's start Mosquitto manually for testing...
    echo Press any key to start Mosquitto manually...
    pause >nul
    
    REM Start manually in background
    start "Mosquitto MQTT Broker" /min mosquitto.exe -c "C:\Program Files\mosquitto\config\mosquitto.conf"
    timeout /t 3 >nul
    
    REM Check if it's running
    tasklist /fi "imagename eq mosquitto.exe" | find "mosquitto.exe" >nul
    if %errorLevel% equ 0 (
        echo Mosquitto started successfully in manual mode
        goto :success
    ) else (
        echo ERROR: Failed to start Mosquitto manually
        pause
        exit /b 1
    )
)

REM Start the service
echo Starting Mosquitto service...
sc start mosquitto
if %errorLevel% neq 0 (
    echo WARNING: Service start failed, trying manual start...
    start "Mosquitto MQTT Broker" /min mosquitto.exe -c "C:\Program Files\mosquitto\config\mosquitto.conf"
    timeout /t 3 >nul
    
    REM Check if it's running
    tasklist /fi "imagename eq mosquitto.exe" | find "mosquitto.exe" >nul
    if %errorLevel% equ 0 (
        echo Mosquitto started successfully in manual mode
    ) else (
        echo ERROR: Failed to start Mosquitto
        pause
        exit /b 1
    )
)

:success

echo.
echo ========================================
echo MQTT Broker Setup Complete!
echo ========================================
echo.
echo Mosquitto MQTT Broker is now running on:
echo   Host: localhost (or your IP address)
echo   Port: 1883
echo.
echo Created users:
echo   - esp32_user (for ESP32 devices)
echo   - edge_processor (for edge processor)
echo.
echo Configuration file: C:\Program Files\mosquitto\config\mosquitto.conf
echo Log file: C:\Program Files\mosquitto\logs\mosquitto.log
echo.
echo Next steps:
echo 1. Update your .env file with local MQTT credentials
echo 2. Test the connection using the provided test scripts
echo 3. Configure your ESP32 with the esp32_user credentials
echo.
echo Service management:
echo   Start:   sc start mosquitto
echo   Stop:    sc stop mosquitto
echo   Status:  sc query mosquitto
echo.
pause
