version: '3.8'

services:
  streamsheets:
    image: cedalo/streamsheets:latest
    container_name: smart-bins-streamsheets
    ports:
      - "1883:1883"    # MQTT Broker
      - "27017:27017"  # MongoDB
      - "6379:6379"    # Redis
      - "8080:8080"    # Streamsheets Web UI
      - "8081:8081"    # Streamsheets Gateway
      - "8083:8083"    # Streamsheets REST API
      - "8088:8088"    # Streamsheets WebSocket
      - "9000:9000"    # Streamsheets Admin
    volumes:
      - streamsheets_data:/var/lib/streamsheets
      - streamsheets_logs:/var/log/streamsheets
    environment:
      - STREAMSHEETS_LICENSE_ACCEPT=true
      - STREAMSHEETS_GATEWAY_HTTP_PORT=8081
      - STREAMSHEETS_GATEWAY_WS_PORT=8088
      - STREAMSHEETS_ADMIN_PORT=9000
      - MQTT_HOST=localhost
      - MQTT_PORT=1883
    restart: unless-stopped
    networks:
      - smart-bins-network

  # Optional: Separate MQTT broker for external connections
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: smart-bins-mosquitto
    ports:
      - "1884:1883"    # External MQTT port
      - "9001:9001"    # WebSocket port
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - mosquitto_data:/mosquitto/data
    restart: unless-stopped
    networks:
      - smart-bins-network

volumes:
  streamsheets_data:
    driver: local
  streamsheets_logs:
    driver: local
  mosquitto_data:
    driver: local

networks:
  smart-bins-network:
    driver: bridge
